CREATE TABLE town (
  townId INTEGER PRIMARY KEY generated by default as identity,
  name VARCHAR(100) NOT NULL,
  nearest_airpor_code CHAR(3) NOT NULL,
  country VARCHAR(100) NOT NULL
);


CREATE TABLE hotel (
  hotelId INTEGER PRIMARY KEY generated by default as identity,
  townId INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  street CHAR(100) NOT NULL,
  house VARCHAR(5) NOT NULL,
  num_of_stars INTEGER NOT NULL DEFAULT 0, CHECK (num_of_stars >= 0 AND num_of_stars <= 5),
  all_inclusive_price INT,
  BB_price INTEGER, CHECK (BB_price >= 0),
  HB_price INTEGER, CHECK (HB_price >= 0),
  FB_price INTEGER, CHECK (FB_price >= 0),
  swimming_pool BOOLEAN,
  parking BOOLEAN,
  gymnasium BOOLEAN,
  spa_center BOOLEAN,
  free_WiFi BOOLEAN,
  private_beach BOOLEAN,
  restaurant BOOLEAN,
  golf_field BOOLEAN,
  bar BOOLEAN,
  FOREIGN KEY (townId) REFERENCES town (townId)
);


CREATE TABLE room (
  roomId INTEGER PRIMARY KEY generated by default as identity,
  hotelId INTEGER NOT NULL,
  max_num_of_people INTEGER NOT NULL, CHECK (max_num_of_people >= 0),
  num_of_beds INTEGER NOT NULL, CHECK (num_of_beds >= 0),
  price INTEGER NOT NULL, CHECK (price >= 0),
  num_of_rooms_in_hotel INTEGER NOT NULL, CHECK (num_of_rooms_in_hotel >= 0),
  air_condition BOOLEAN,
  chimney BOOLEAN,
  balcon BOOLEAN,
  kitchen BOOLEAN,
  private_bathroom BOOLEAN,
  mini_bar BOOLEAN,
  tea_coffee BOOLEAN,
  TV BOOLEAN,
  FOREIGN KEY (hotelId) REFERENCES hotel (hotelId)
);


CREATE TABLE flight (
  flightId INTEGER PRIMARY KEY generated by default as identity,
  departure_airport_townId INTEGER NOT NULL,
  arrival_airport_townId INTEGER NOT NULL,
  price INTEGER NOT NULL, CHECK (price >= 0),
  flight_number VARCHAR(6) NOT NULL,
  departure_time TIME NOT NULL,
  arrival_time TIME NOT NULL,
  FOREIGN KEY (departure_airport_townId) REFERENCES town (townId),
  FOREIGN KEY (arrival_airport_townId) REFERENCES town (townId)
 );


CREATE TABLE tour (
  tourId INTEGER PRIMARY KEY generated by default as identity,
  flightId INTEGER NOT NULL,
  roomId INTEGER NOT NULL,
  price INTEGER NOT NULL, CHECK (price >= 0),
  FOREIGN KEY (flightId) REFERENCES flight (flightId),
  FOREIGN KEY (roomId) REFERENCES room (roomId)
 );


CREATE TABLE person (
  personId INTEGER PRIMARY KEY generated by default as identity,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  phone_num VARCHAR(14) NOT NULL,
  email VARCHAR(100) NOT NULL
);


CREATE TABLE m_order (
  orderId INTEGER PRIMARY KEY generated by default as identity,
  personId INTEGER NOT NULL,
  FOREIGN KEY (personId) REFERENCES person (personId)
);


CREATE TABLE flight_order (
  flight_orderId INTEGER PRIMARY KEY generated by default as identity,
  orderId INTEGER NOT NULL,
  flightId INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  FOREIGN KEY (orderId) REFERENCES m_order (orderId),
  FOREIGN KEY (flightId) REFERENCES flight (flightId)
);


CREATE TABLE tour_order (
  tour_orderId INTEGER PRIMARY KEY generated by default as identity,
  orderId INTEGER NOT NULL,
  tourId INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  FOREIGN KEY (orderId) REFERENCES m_order (orderId),
  FOREIGN KEY (tourId) REFERENCES tour (tourId)
);


CREATE TABLE room_order (
  room_orderId INTEGER PRIMARY KEY generated by default as identity,
  orderId INTEGER NOT NULL,
  roomId INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  FOREIGN KEY (orderId) REFERENCES m_order (orderId),
  FOREIGN KEY (roomId) REFERENCES room (roomId)
);


CREATE TABLE favourites (
  favouritesId INTEGER PRIMARY KEY generated by default as identity,
  personId INTEGER NOT NULL,
  FOREIGN KEY (personId) REFERENCES person (personId)
);


CREATE TABLE flight_favourites (
  flight_favouritesId INTEGER PRIMARY KEY generated by default as identity,
  favouritesId INTEGER NOT NULL,
  flightId INTEGER NOT NULL,
  FOREIGN KEY (favouritesId) REFERENCES favourites (favouritesId),
  FOREIGN KEY (flightId) REFERENCES flight (flightId)
);


CREATE TABLE tour_favourites (
  tour_favouritesId INTEGER PRIMARY KEY generated by default as identity,
  favouritesId INTEGER NOT NULL,
  tourId INTEGER NOT NULL,
  FOREIGN KEY (favouritesId) REFERENCES favourites (favouritesId),
  FOREIGN KEY (tourId) REFERENCES tour (tourId)
);


CREATE TABLE hotel_favourites (
  hotel_favouritesId INTEGER PRIMARY KEY generated by default as identity,
  favouritesId INTEGER NOT NULL,
  hotelId INTEGER NOT NULL,
  FOREIGN KEY (favouritesId) REFERENCES favourites (favouritesId),
  FOREIGN KEY (hotelId) REFERENCES hotel (hotelId)
);


CREATE TABLE people_data (
  people_dataId INTEGER PRIMARY KEY generated by default as identity,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  insurance VARCHAR(30),
  visa VARCHAR(30),
  passport CHAR(9) NOT NULL
);


CREATE TABLE people_data_order (
  people_data_orderId INTEGER PRIMARY KEY generated by default as identity,
  people_dataId INTEGER NOT NULL,
  orderId INTEGER NOT NULL,
  FOREIGN KEY (people_dataId) REFERENCES people_data (people_dataId),
  FOREIGN KEY (orderId) REFERENCES m_order (orderId)
);
